export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#b4c5ff",
        "surface-variant": "#e6e3d2",
        "on-error-container": "#93000a",
        "on-secondary-fixed-variant": "#005312",
        "on-error": "#ffffff",
        "secondary-fixed-dim": "#82db7e",
        "surface": "#fdfae8",
        "surface-bright": "#fdfae8",
        "secondary-container": "#9df898",
        "background": "#fdfae8",
        "surface-container": "#f1eedd",
        "inverse-surface": "#313126",
        "on-secondary-container": "#1a7425",
        "tertiary-fixed-dim": "#fdbc13",
        "tertiary-fixed": "#ffdea3",
        "primary-fixed": "#dbe1ff",
        "error-container": "#ffdad6",
        "outline": "#737686",
        "tertiary-container": "#7e5b00",
        "surface-container-low": "#f7f4e3",
        "secondary": "#106d20",
        "primary-container": "#0055e1",
        "on-tertiary-fixed": "#261900",
        "inverse-primary": "#b4c5ff",
        "surface-tint": "#0053db",
        "inverse-on-surface": "#f4f1e0",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#d3dcff",
        "on-surface": "#1c1c12",
        "surface-container-high": "#ece9d8",
        "on-primary-fixed": "#00174b",
        "on-primary-fixed-variant": "#003ea8",
        "on-tertiary-container": "#ffd78c",
        "surface-dim": "#dddaca",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#9df898",
        "on-background": "#1c1c12",
        "on-surface-variant": "#434655",
        "surface-container-highest": "#e6e3d2",
        "outline-variant": "#c3c6d7",
        "on-secondary-fixed": "#002204",
        "on-tertiary-fixed-variant": "#5d4200",
        "primary": "#0040ae",
        "tertiary": "#604500"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Work Sans"],
        "label": ["Work Sans"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
